/**
     * Es el constructor que inicializa la interfaz de Registro. 
     *//*//GEN-FIRST:event_jButton_VolverActionPerformed
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license//GEN-LAST:event_jButton_VolverActionPerformed
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static ventanas.Login.clienteActual;
import manejoarchivos.Convertir;
import static ventanas.Login.banco;
import java.text.DecimalFormat;

/**
 *Esta clase permite la conversion de una moneda a otra con tasas de conversion preestablecidas
 */
public class ConvMoneda extends javax.swing.JFrame {
    /**
     * Es el constructor que inicializa la interfaz de ConvMoneda. 
     */
    
    private Convertir moneda;

    public ConvMoneda() {
        initComponents();
        setSize(400, 600);
        setResizable(false);
        setTitle("Abonar - Cajero Automatico PROTECH");
        setLocationRelativeTo(null);

        ImageIcon wallpaper = new ImageIcon("src/images/fondo_login.png");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_Wallpaper.getWidth(), jLabel_Wallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabel_Wallpaper.setIcon(icono);
        this.repaint();

        ImageIcon wallpaper_logo = new ImageIcon("src/images/logo_protech.png");
        Icon icono_logo = new ImageIcon(wallpaper_logo.getImage().getScaledInstance(jLabel_Logo.getWidth(), jLabel_Logo.getHeight(), Image.SCALE_DEFAULT));
        jLabel_Logo.setIcon(icono_logo);
        this.repaint();

        //Imagen de ConvMoneda
        ImageIcon imagAbonar = new ImageIcon("src/images/alas_dinero.png");
        Icon icono_abonar = new ImageIcon(imagAbonar.getImage().getScaledInstance(jLabel_ImaAbonar.getWidth(), jLabel_ImaAbonar.getHeight(), Image.SCALE_DEFAULT));
        jLabel_ImaAbonar.setIcon(icono_abonar);
        this.repaint();
    }
/**
     * Este metodo sebreescribe getIconImage para esteblecer el icono de la aplicacion.
     * Este cambio se debe a un error en la carpeta de recursos. 
     * @return el icono de imagen predeterminado como icono de ventana
     */
    @Override
    public Image getIconImage() {  //CAMBIAR DIRECCION DEL ICONO POR ERROR DE CARPETA DE RECURSOS
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/logo_protech.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel_Titulo = new javax.swing.JLabel();
        Derechos_Autor = new javax.swing.JLabel();
        jLabel_ImaAbonar = new javax.swing.JLabel();
        Aclaracion = new javax.swing.JLabel();
        jLabel_Logo = new javax.swing.JLabel();
        jButton_Volver = new javax.swing.JButton();
        jLabel_Subtitulo2 = new javax.swing.JLabel();
        jButton_ConvertirMon = new javax.swing.JButton();
        jTextField_MonedaConv = new javax.swing.JTextField();
        jLabel_SaldoActual = new javax.swing.JLabel();
        jLabel_MonedaActual = new javax.swing.JLabel();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Titulo.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel_Titulo.setText("CONVERTIR MONEDA");
        getContentPane().add(jLabel_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        Derechos_Autor.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        Derechos_Autor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Derechos_Autor.setText("ProTech2024 © ");
        Derechos_Autor.setToolTipText("");
        getContentPane().add(Derechos_Autor, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 530, -1, -1));
        getContentPane().add(jLabel_ImaAbonar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 50, 50));

        Aclaracion.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        Aclaracion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Aclaracion.setText("Opciones: Dolar/Euro/Sol/Real/Yen/Boliviano");
        Aclaracion.setToolTipText("");
        getContentPane().add(Aclaracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, -1, -1));
        getContentPane().add(jLabel_Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 100, 100));

        jButton_Volver.setBackground(new java.awt.Color(255, 51, 0));
        jButton_Volver.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jButton_Volver.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Volver.setText("Volver");
        jButton_Volver.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 3, true));
        jButton_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_VolverActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 150, 40));

        jLabel_Subtitulo2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel_Subtitulo2.setText("Escribe la moneda");
        getContentPane().add(jLabel_Subtitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jButton_ConvertirMon.setBackground(new java.awt.Color(0, 0, 0));
        jButton_ConvertirMon.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jButton_ConvertirMon.setForeground(new java.awt.Color(255, 255, 255));
        jButton_ConvertirMon.setText("Convertir");
        jButton_ConvertirMon.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 3, true));
        jButton_ConvertirMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ConvertirMonActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_ConvertirMon, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 150, 40));

        jTextField_MonedaConv.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jTextField_MonedaConv.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(jTextField_MonedaConv, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 230, 50));

        jLabel_SaldoActual.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        getContentPane().add(jLabel_SaldoActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 300, 20));

        jLabel_MonedaActual.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        getContentPane().add(jLabel_MonedaActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 300, 20));
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 600));

        pack();
    }// </editor-fold>                        
/**
 * Esta accion tiene el objetivo de volver a la "Pagina Principal" de la interfaz 
 */
    private void jButton_VolverActionPerformed(java.awt.event.ActionEvent evt) {                                               
        new PagPrincipal().setVisible(true);
        this.dispose();
    }                                              

    private void jButton_ConvertirMonActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        String tipoMoneda = jTextField_MonedaConv.getText(); // Moneda ingresada por el usuario
    String tipoMonedaA = clienteActual.getMoneda(); // Moneda actual del cliente
    DecimalFormat df = new DecimalFormat("#.##"); // Formato para 2 decimales

    // Validar que el campo no esté vacío
    if (tipoMoneda.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Por favor ingresa una moneda válida.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Intentar convertir la moneda del cliente
    Convertir conversion = new Convertir(tipoMoneda, clienteActual.getSaldo(), tipoMonedaA);
    
    // Verificar si la conversión fue exitosa (si las monedas son válidas y existe una tasa de conversión)
    if (conversion.monedaExiste()) {
        double nuevoSaldo = conversion.convertirMoneda(); // Convertimos el saldo
        clienteActual.setSaldo(nuevoSaldo); // Actualizamos el saldo del cliente
        clienteActual.setMoneda(conversion.getNuevaMoneda()); // Actualizamos la moneda actual del cliente

        // Guardamos los cambios en el banco
        banco.guardarClientes();

        // Mostramos el saldo actualizado en la interfaz
        String valorFormateado = df.format(clienteActual.getSaldo());
        jLabel_SaldoActual.setText("Su saldo actual es: " + valorFormateado);
        jLabel_MonedaActual.setText("Su moneda actual es: " + clienteActual.getMoneda());

        JOptionPane.showMessageDialog(null, "Conversión realizada con éxito.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
    } else {
        JOptionPane.showMessageDialog(null, "No se pudo realizar la conversión. Verifica la moneda ingresada.", "Error", JOptionPane.ERROR_MESSAGE);
    }

    // Limpiar el campo de texto
    jTextField_MonedaConv.setText("");    
    }                                                    

    /**
     * /**
     * Metodo principal que ejecuta la inicializacion de la interfaz de ConvMoneda.
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConvMoneda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConvMoneda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConvMoneda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConvMoneda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConvMoneda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel Aclaracion;
    private javax.swing.JLabel Derechos_Autor;
    private javax.swing.JButton jButton_ConvertirMon;
    private javax.swing.JButton jButton_Volver;
    private javax.swing.JLabel jLabel_ImaAbonar;
    private javax.swing.JLabel jLabel_Logo;
    private javax.swing.JLabel jLabel_MonedaActual;
    private javax.swing.JLabel jLabel_SaldoActual;
    private javax.swing.JLabel jLabel_Subtitulo2;
    private javax.swing.JLabel jLabel_Titulo;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JTextField jTextField_MonedaConv;
    // End of variables declaration                   
}
